### ISSUE TITLE
Request: To have more complex csv with data and for nornir_scrapli usecases

### ISSUE THREAD

**Issue by jnyany** [matman26/nornir_csv#2]
I use more fields in yaml for example of host file below, how can this be documented in CSV?
specially for headers like, data: connection_options:, scrapli:, and scrapli_netconf:

---
rtr1:
  hostname: 10.91.11.11
  data:
    interface: TenGigE0/0/0/16
    localmepid: 1
    remotemepid: 2
    rd: 1600
    evi: 2600
    xrsw: 7.1.2
  connection_options: 
    scrapli:
      platform: cisco_iosxr
      port: 22
      extras:
        ssh_config_file: True
        auth_strict_key: False
    scrapli_netconf:
      port: 830
      extras:
        ssh_config_file: True
        auth_strict_key: False

**Comment by matman26** [comment]
I was actually thinking about the issue of connection options a while back. One idea would be to have it as another csv file:
```csv
connection_options, port, platform, ssh_config_file, auth_strict_key
scrapli,  22, cisco_iosxr, True, False
netmiko, 22, cisco_iosxr, True, False
```

The hosts csv file is context-sensitive, which means that any column that matches to base attributes (name, hostname, platform, etc...) will be put into the appropriate slots for the host while everything else will be put in the 'data' dict. The same could be done to `connection_options.csv`: any column that's not a base attribute could be put into the 'extras' dict for the connection options. With this setup, the above csv would yield an equivalent to the YAML below:

```yaml
connection_options:
 scrapli:
  platform: cisco_iosxr
  port: 22
  extras:
   auth_strict_key: False
   ssh_config_file: True
 netmiko:
  platform: cisco_iosxr
  port: 22
  extras:
   auth_strict_key: False
   ssh_config_file: True

```

In this sense, writing to the `data` dict of a host is already supported, but setting connection options is currently not (it will be added in the next commits though).
